### ISSUE TITLE
Pointing range affected

### ISSUE THREAD

**Issue by pswilde** [MrRar/edit_skin#13]
Hi, thanks for your hard work on this. It's a great mod.

I've noticed that the pointing range seems to be affected in this mod - like #7 however it still seems to be happening to me, I'm using the latest commit. Pointing range with this mod enabled is 4, disabling this mod makes it 10 again.

I think whatever is happening is somewhere around line 583 in init.lua, as if I set `local range = 10`, I can have this mod enabled with the default (for minetest game) 10 block pointing range.

I can work around this with the adjustment above, so no massive problem, but if you know of why this could be happening that would be ideal.

Thanks

**Comment by MrRar** [comment]
Looks like minetest_game broke edit_skin with this PR: https://github.com/minetest/minetest_game/pull/2984https://github.com/minetest/minetest_game/pull/2984

**Comment by MrRar** [comment]
Should be fixed now if you want to try the latest version.
