### ISSUE TITLE
active_block_range affected?

### ISSUE THREAD

**Issue by animaux** [MrRar/edit_skin#7]
After installing edit_skin in `minetest 5.6.0` on a server with a game in creative mode, I am not able to reach blocks further away than approximately 3 or 4 blocks. Setting `active_block_range` on the server doesn’t seem to have any effect.

Though a connection with edit_skin seems unlikely, it was the only thing I changed before this behavior started. Has anybody else noticed something similar?

**Comment by MrRar** [comment]
edit_skin creates a mesh hand node and puts it in the hand inventory. I guess the mesh hand node is overwriting the range of the default hand even though it does not include a range property (?) I will look into this.

https://github.com/MrRar/edit_skin/blob/6605aafabf54c2f8051b8b3e348fe51d1dee0b78/init.lua#L140

**Comment by animaux** [comment]
Many thanks, that sound plausible for my uninformed ears `;)`

**Comment by MrRar** [comment]
I fixed the problem of the creative mode hand range not being respected because of edit_skin.

BTW I don't think active_block_range means what you think it does. Here is the description:
```
The radius of the volume of blocks around every player that is subject to the
active block stuff, stated in mapblocks (16 nodes).
In active blocks objects are loaded and ABMs run.
This is also the minimum range in which active objects (mobs) are maintained.
This should be configured together with active_object_send_range_blocks.
```

There's no setting in the Minetest game to control the hand range in creative mode. It's always set to 10.

**Comment by animaux** [comment]
Thanks for fixing this so fast and clarifying! Will try it just now.

**Comment by animaux** [comment]
Works perfect many thanks!
